spring.application.name=taskflow

#
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=${DB_USERNAME:taskflow}
spring.datasource.password=${DB_PASSWORD:taskflow}

#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

#
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT auth
app.auth.jwt.secret=${JWT_SECRET:taskflow-jwt-secret-change-me-at-runtime-32-chars-min}
app.auth.jwt.access-token-ttl=PT15M
app.auth.jwt.refresh-token-ttl=P7D
app.auth.jwt.refresh-cookie-name=refresh_token
app.auth.jwt.refresh-cookie-path=/api/v1/auth/refresh
app.auth.jwt.refresh-cookie-same-site=Strict
app.auth.jwt.refresh-cookie-secure=false
